# Generated by Django 4.1.1 on 2022-09-14 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Resident",
            fields=[
                (
                    "tg_user_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=12)),
                ("socials", models.URLField()),
                ("birthdate", models.DateField()),
                ("photo", models.URLField()),
                ("company", models.CharField(max_length=100)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tobibotapp.branch",
                    ),
                ),
            ],
        ),
    ]
