# Generated by Django 4.1.1 on 2022-09-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tobibotapp", "0004_resident_building_resident_office"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resident",
            name="description",
            field=models.TextField(default="", max_length=500),
        ),
    ]
