# Generated by Django 4.1.1 on 2022-09-14 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tobibotapp", "0005_alter_resident_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={
                "verbose_name": "Направление деятельности",
                "verbose_name_plural": "Направления деятельности",
            },
        ),
        migrations.AlterField(
            model_name="branch",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название направления"),
        ),
        migrations.AlterField(
            model_name="building",
            name="address",
            field=models.CharField(max_length=100, verbose_name="Адрес (описание)"),
        ),
        migrations.AlterField(
            model_name="resident",
            name="birthdate",
            field=models.DateField(verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="resident",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tobibotapp.branch",
                verbose_name="Направление",
            ),
        ),
        migrations.AlterField(
            model_name="resident",
            name="building",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tobibotapp.building",
                verbose_name="Здание инкубатора",
            ),
        ),
        migrations.AlterField(
            model_name="resident",
            name="company",
            field=models.CharField(max_length=100, verbose_name="Название компании"),
        ),
        migrations.AlterField(
            model_name="resident",
            name="description",
            field=models.TextField(default="", max_length=500, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="resident",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="resident",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="resident",
            name="office",
            field=models.CharField(default="", max_length=50, verbose_name="Офис"),
        ),
        migrations.AlterField(
            model_name="resident",
            name="phone",
            field=models.CharField(max_length=12, verbose_name="Телефон"),
        ),
        migrations.AlterField(
            model_name="resident",
            name="photo",
            field=models.ImageField(upload_to="", verbose_name="Ссылка на фотографию"),
        ),
        migrations.AlterField(
            model_name="resident",
            name="socials",
            field=models.URLField(default="", verbose_name="Страница в соцсети"),
        ),
        migrations.AlterField(
            model_name="resident",
            name="tg_user_id",
            field=models.IntegerField(
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Telegram ID",
            ),
        ),
    ]
