# Generated by Django 4.1.1 on 2022-09-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tobibotapp", "0006_alter_branch_options_alter_branch_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resident",
            name="photo",
            field=models.ImageField(upload_to="images/", verbose_name="Фотография"),
        ),
    ]
