# Generated by Django 4.1.1 on 2022-09-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tobibotapp", "0007_alter_resident_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="tg_group_invite",
            field=models.URLField(
                default="", verbose_name="Ссылка-приглашение в группу телеграм"
            ),
        ),
    ]
