# Generated by Django 4.1.1 on 2022-09-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tobibotapp", "0008_building_tg_group_invite"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="email",
            field=models.EmailField(default="", max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="resident",
            name="website",
            field=models.URLField(default="", verbose_name="Сайт компании"),
        ),
        migrations.AlterField(
            model_name="resident",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="Фотография"
            ),
        ),
    ]
