# Generated by Django 4.1.1 on 2022-09-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tobibotapp", "0009_resident_email_resident_website_alter_resident_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="tg_group_invite",
            field=models.URLField(
                blank=True,
                default="",
                verbose_name="Ссылка-приглашение в группу телеграм",
            ),
        ),
        migrations.RemoveField(
            model_name="resident",
            name="branch",
        ),
        migrations.AddField(
            model_name="resident",
            name="branch",
            field=models.ManyToManyField(
                to="tobibotapp.branch", verbose_name="Направление"
            ),
        ),
    ]
