# Generated by Django 4.1.1 on 2022-09-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tobibotapp", "0010_alter_building_tg_group_invite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="tg_username",
            field=models.CharField(
                default="",
                max_length=33,
                unique=True,
                verbose_name="Имя пользователя Telegram",
            ),
        ),
    ]
