# Generated by Django 4.1.1 on 2022-09-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tobibotapp", "0015_resident_email_confirm_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resident",
            name="email_confirm_code",
            field=models.CharField(
                default="", max_length=9, verbose_name="Код подтверждения email"
            ),
        ),
        migrations.AlterField(
            model_name="resident",
            name="tg_user_id",
            field=models.BigIntegerField(
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Telegram ID",
            ),
        ),
    ]
