# Generated by Django 4.1.1 on 2022-09-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tobibotapp", "0017_alter_resident_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="reg_state",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Статус регистрации"
            ),
        ),
    ]
