# Generated by Django 4.1.1 on 2022-09-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tobibotapp", "0019_alter_resident_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resident",
            name="photo",
            field=models.ImageField(
                blank=True, default="", upload_to="", verbose_name="Фотография"
            ),
        ),
    ]
