# Generated by Django 4.1.1 on 2022-09-26 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tobibotapp", "0020_alter_resident_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resident",
            name="branch",
        ),
        migrations.AddField(
            model_name="resident",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tobibotapp.branch",
                verbose_name="Направление бизнеса",
            ),
        ),
    ]
