# Generated by Django 4.1.1 on 2022-09-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tobibotapp", "0021_remove_resident_branch_resident_branch"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resident",
            old_name="birthdate",
            new_name="birth_date",
        ),
    ]
