# Generated by Django 4.1.1 on 2022-09-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tobibotapp", "0022_rename_birthdate_resident_birth_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resident",
            name="reg_state",
        ),
        migrations.AddField(
            model_name="resident",
            name="registration_completed",
            field=models.BooleanField(
                default=False, verbose_name="Регистрация завершена"
            ),
        ),
    ]
