# Generated by Django 4.1.1 on 2022-11-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tobibotapp", "0024_alter_resident_tg_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", max_length=1000, verbose_name="Описание"
                    ),
                ),
                (
                    "place",
                    models.CharField(max_length=100, verbose_name="Место проведения"),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(
                        blank=True, default="1900-01-01 00:00", verbose_name="Начало"
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True, default="1900-01-01 00:00", verbose_name="Конец"
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True, default="", upload_to="", verbose_name="Картинка"
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
    ]
