# Generated by Django 4.1.1 on 2022-11-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tobibotapp", "0025_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_datetime",
            field=models.DateTimeField(blank=True, verbose_name="Конец"),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_datetime",
            field=models.DateTimeField(blank=True, verbose_name="Начало"),
        ),
    ]
